// Phase 2/3 E2E(2ユーザー): フレンド申請・承認 → 進捗共有 → 応援 → 一緒に勉強 → グループ → プライバシー → ログアウト/退会
import { addTask, BASE, check, failed, launch, newUser, shot, signup, tid } from './lib.mjs';

const norm = (s) => (s ?? '').replace(/\s+/g, ' ').trim();
const stamp = Date.now();
const browser = await launch();
const a = await newUser(browser, 'ゆうき');
const b = await newUser(browser, 'はる');

console.log('1. 2人が登録');
await signup(a.page, { nickname: 'ゆうき', avatar: 'cat', email: `a_${stamp}@example.com` });
await signup(b.page, { nickname: 'はる', avatar: 'frog', email: `b_${stamp}@example.com` });

console.log('2. フレンド申請 → 承認');
await a.page.goto(`${BASE}/friends`, { waitUntil: 'domcontentloaded' });
await tid(a.page, 'empty-add-friend').waitFor({ timeout: 20000 });
check(true, '友だちがいないときは追加を促す表示');
await tid(a.page, 'add-friend').click();
await tid(a.page, 'my-code').waitFor();
await a.page.waitForFunction(() => /^[A-Z2-9]{8}$/.test(document.querySelector('[data-testid="my-code"]')?.textContent ?? ''));
const codeA = norm(await tid(a.page, 'my-code').textContent());
check(/^[A-Z2-9]{8}$/.test(codeA), `自分のフレンドコード ${codeA}`);
await shot(a.page, '20-add-friend');

await b.page.goto(`${BASE}/friends`, { waitUntil: 'domcontentloaded' });
await tid(b.page, 'add-friend').click();
await tid(b.page, 'friend-code-input').fill('BADCODE');
await tid(b.page, 'send-request').click();
check(await b.page.getByText('8文字の英数字').isVisible(), '不正なコード形式はエラー');
await tid(b.page, 'friend-code-input').fill('ZZZZZZZ2');
await tid(b.page, 'send-request').click();
await b.page.getByText('見つからなかった').waitFor({ timeout: 10000 });
check(true, '存在しないコードは「見つからなかったよ」(技術的なエラーは出さない)');
await tid(b.page, 'friend-code-input').fill(codeA);
await tid(b.page, 'send-request').click();
await b.page.getByText('申請を送ったよ').waitFor({ timeout: 10000 });
check(true, 'フレンド申請を送信');
await tid(b.page, 'friend-code-input').fill(codeA);
await tid(b.page, 'send-request').click();
await b.page.getByText('すでに申請ずみ').waitFor({ timeout: 10000 });
check(true, '二重申請は「すでに申請ずみだよ」');

await a.page.goto(`${BASE}/friends`, { waitUntil: 'domcontentloaded' });
await tid(a.page, 'add-friend').click();
await tid(a.page, 'accept-はる').waitFor({ timeout: 20000 });
await shot(a.page, '21-request-incoming');
await tid(a.page, 'accept-はる').click();
await a.page.getByText('フレンドになったよ').waitFor({ timeout: 10000 });
check(true, '申請を承認してフレンドに');

console.log('3. 進捗共有: はるが計画して勉強開始 → ゆうきに見える');
await b.page.goto(`${BASE}/quest`, { waitUntil: 'domcontentloaded' });
await addTask(b.page, { title: '英単語', minutes: 20 });
await addTask(b.page, { title: '数学', minutes: 30 });
await tid(b.page, 'start-英単語').click();
await tid(b.page, 'timer-finish').click();
await tid(b.page, 'done-title').waitFor({ timeout: 15000 });
await tid(b.page, 'next-task').click(); // 数学を開始(勉強中)
await tid(b.page, 'timer-clock').waitFor({ timeout: 15000 });

await a.page.goto(`${BASE}/friends`, { waitUntil: 'domcontentloaded' });
await tid(a.page, 'friend-はる').waitFor({ timeout: 20000 });
const row = norm(await tid(a.page, 'friend-はる').textContent());
check(row.includes('数学を勉強中'), '友だち一覧に「数学を勉強中」');
check(row.includes('1/2'), '今日の達成数 1/2');
check((await tid(a.page, 'live-banner').count()) === 1, 'LIVEバナー(いま◯人が勉強中)');
check(norm(await tid(a.page, 'live-banner').textContent()).includes('数学'), 'バナーに教科名');
await shot(a.page, '22-friends-list');

console.log('4. 応援リアクション');
await tid(a.page, 'cheer-はる').click();
await tid(a.page, 'react-はる-fire').click();
await a.page.getByText('応援を送ったよ').waitFor({ timeout: 10000 });
check(true, '🔥 を送信');
await tid(a.page, 'cheer-はる').click();
check(await tid(a.page, 'react-はる-fire').isDisabled(), '同じ種類は「送ったよ」で押せない');
await b.page.goto(`${BASE}/home`, { waitUntil: 'domcontentloaded' });
await tid(b.page, 'bell').click();
await b.page.getByText('ゆうきさんから').waitFor({ timeout: 15000 });
check(true, 'はるのお知らせに「🔥 ゆうきさんから」');
await shot(b.page, '23-notifications');
await b.page.getByTestId('sheet-close').click();

console.log('5. 一緒に勉強する(スタディパーティー)');
await a.page.goto(`${BASE}/study-party`, { waitUntil: 'domcontentloaded' });
await tid(a.page, 'party-subject').waitFor({ timeout: 20000 });
check(norm(await tid(a.page, 'party-subject').textContent()) === '数学', 'ルームの教科は「数学」');
check((await tid(a.page, 'party-member-はる').count()) === 1, 'メンバーにはる');
await shot(a.page, '24-study-party');
await tid(a.page, 'party-join').click();
await a.page.waitForURL(/\/quest\/[0-9a-f-]{36}/, { timeout: 15000 });
await tid(a.page, 'timer-clock').waitFor();
check(norm(await tid(a.page, 'timer-title').textContent()) === '数学', '「一緒にやる」で数学のタイマーが始まる');
await b.page.goto(`${BASE}/study-party`, { waitUntil: 'domcontentloaded' });
await tid(b.page, 'party-member-ゆうき').waitFor({ timeout: 20000 });
check((await tid(b.page, 'party-member-ゆうき').count()) === 1, 'はる側にもゆうきが見える(2人で勉強中)');

console.log('6. グループ・協力チャレンジ');
await a.page.goto(`${BASE}/groups`, { waitUntil: 'domcontentloaded' });
await tid(a.page, 'empty-create-group').waitFor({ timeout: 20000 });
await tid(a.page, 'create-group').click();
await tid(a.page, 'group-create-submit').click();
check(await a.page.getByText('グループ名を入力してね').isVisible(), '空のグループ名はエラー');
await tid(a.page, 'group-name-input').fill('テスト前がんばる会');
await tid(a.page, 'group-create-submit').click();
await a.page.waitForURL(/\/groups\/[0-9a-f-]{36}/, { timeout: 15000 });
await tid(a.page, 'group-title').waitFor();
check(norm(await tid(a.page, 'group-progress').textContent()).startsWith('0 / 5'), '協力クエスト 0 / 5日分(1人×5日)');
await tid(a.page, 'group-invite').click();
await tid(a.page, 'invite-はる').click();
await a.page.getByText('招待したよ').waitFor({ timeout: 10000 });
check(true, 'フレンドを招待');
await a.page.getByTestId('sheet-close').click();
await b.page.goto(`${BASE}/groups`, { waitUntil: 'domcontentloaded' });
await tid(b.page, 'join-テスト前がんばる会').waitFor({ timeout: 20000 });
await shot(b.page, '25-group-invite');
await tid(b.page, 'join-テスト前がんばる会').click();
await tid(b.page, 'group-テスト前がんばる会').waitFor({ timeout: 15000 });
check(true, 'はるが招待を承認して参加');
// はるが今日のクエストをクリア → グループの進捗が進む
await b.page.goto(`${BASE}/home`, { waitUntil: 'domcontentloaded' });
await tid(b.page, 'home-cta-start').waitFor({ timeout: 20000 });
await tid(b.page, 'home-cta-start').click();
await tid(b.page, 'timer-clock').waitFor({ timeout: 15000 });
await tid(b.page, 'timer-finish').click();
await b.page.waitForURL('**/complete', { timeout: 20000 });
check(true, 'はるが今日クリア(ハンコ獲得画面)');
await a.page.goto(`${BASE}/groups`, { waitUntil: 'domcontentloaded' });
await tid(a.page, 'group-テスト前がんばる会').click();
await tid(a.page, 'group-progress').waitFor({ timeout: 20000 });
check(norm(await tid(a.page, 'group-progress').textContent()).startsWith('1 / 10'), 'ゆうき側の進捗が 1 / 10日分(2人×5日)');
check(norm(await tid(a.page, 'group-hint').textContent()).includes('2 / 10'), '「あなたが今日クリアすると 2 / 10」');
check(norm(await tid(a.page, 'gmember-はる').textContent()).includes('クリア'), 'メンバーはるは「クリア！」');
await shot(a.page, '26-group-detail');

console.log('7. プライバシー設定: 教科名を隠す');
await b.page.goto(`${BASE}/settings`, { waitUntil: 'domcontentloaded' });
await tid(b.page, 'share-subject').waitFor({ timeout: 20000 });
const before = await b.page.getByRole('switch').isChecked();
await tid(b.page, 'share-subject').click();
await b.page.waitForTimeout(900);
await b.page.reload({ waitUntil: 'domcontentloaded' });
await b.page.getByRole('switch').waitFor({ timeout: 20000 });
check((await b.page.getByRole('switch').isChecked()) === !before, 'プライバシー設定(教科名を見せる)がDBに保存されリロード後も保持');
await shot(b.page, '27-settings');

console.log('8. ログアウト → 再ログイン → 退会');
await tid(b.page, 'logout').click();
await b.page.waitForURL('**/login', { timeout: 15000 });
check(true, 'ログアウトでログイン画面へ');
await tid(b.page, 'login-email').fill(`b_${stamp}@example.com`);
await tid(b.page, 'login-password').fill('wrong-password');
await tid(b.page, 'login-submit').click();
await b.page.getByText('メールアドレスかパスワードがちがう').waitFor({ timeout: 10000 });
check(true, '誤ったパスワードは分かりやすい日本語エラー');
await tid(b.page, 'login-password').fill('password123');
await tid(b.page, 'login-submit').click();
await b.page.waitForURL('**/home', { timeout: 15000 });
check(true, '再ログインで /home へ');
await b.page.goto(`${BASE}/settings`, { waitUntil: 'domcontentloaded' });
await tid(b.page, 'delete-account').click();
await tid(b.page, 'delete-confirm').click();
await b.page.waitForURL('**/login', { timeout: 20000 });
check(true, 'アカウント削除でログイン画面へ');
await tid(b.page, 'login-email').fill(`b_${stamp}@example.com`);
await tid(b.page, 'login-password').fill('password123');
await tid(b.page, 'login-submit').click();
await b.page.getByText('メールアドレスかパスワードがちがう').waitFor({ timeout: 10000 });
check(true, '削除後はログインできない');
await a.page.goto(`${BASE}/friends`, { waitUntil: 'domcontentloaded' });
await tid(a.page, 'empty-add-friend').waitFor({ timeout: 20000 });
check((await tid(a.page, 'friend-はる').count()) === 0, '削除したユーザーは友だち一覧から消える');

const errs = [...a.errors, ...b.errors];
console.log(`\nJS errors: ${errs.length}`);
errs.forEach((e) => console.log('  ', e));
await browser.close();
const ok = failed() === 0 && errs.length === 0;
console.log(ok ? '\nPHASE2/3 E2E: PASS' : `\nPHASE2/3 E2E: FAIL (${failed()} checks, ${errs.length} js errors)`);
process.exit(ok ? 0 : 1);
